on:
  push:
    branches:
    - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Pull Request Action
      uses: repo-sync/pull-request@v2.6
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
